<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Sva.Auth.Application</RootNamespace>
    <AssemblyName>Sva.Auth.Application</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sva.Auth.Domain\Sva.Auth.Domain.csproj" />
  </ItemGroup>

</Project>
