<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Sva.Auth.Infrastructure</RootNamespace>
    <AssemblyName>Sva.Auth.Infrastructure</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sva.Auth.Application\Sva.Auth.Application.csproj" />
  </ItemGroup>

</Project>
