<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <PublishAot>true</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <Protobuf Include="Protos\greet.proto" GrpcServices="Server" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sva.Auth.Application\Sva.Auth.Application.csproj" />
    <ProjectReference Include="..\Sva.Auth.Infrastructure\Sva.Auth.Infrastructure.csproj" />
  </ItemGroup>

</Project>
